name: Lighthouse CI on Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PNPM_VERSION: 8.9.0
  NODE_VERSION: 18.15.0
  PACKAGE_MANAGER: "pnpm"

jobs:
  lhci:
    name: Lighthouse on Container
    runs-on: ubuntu-latest
    container: # This action must be run inside a container that has necessary dependencies for Lighthouse
      image: patrickhulce/lhci-client:latest
      options: --user root # This action must also be run as root user inside the container
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 20 # For Lighthouse to find the appropriate SHA to compare against, we fetch a larger Git history than usual

      - name: 🛠 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.PACKAGE_MANAGER }}

      - name: pnpm install, build
        run: |
          pnpm install
          pnpm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun
